import os
import google.generativeai as genai
import gradio as gr

# Set up Google API key from environment variable
API_KEY = os.getenv("GOOGLE_API_KEY")
if not API_KEY:
    raise ValueError("GOOGLE_API_KEY not set. Add it in Hugging Face Space Secrets.")

# Configure the Google Generative AI client
genai.configure(api_key=API_KEY)

def generate_career_plan(education, skills, internships, interests):
    """Generate a dynamic, unique career plan using Google Gemini API."""
    # Enhanced prompt for varied, specific responses
    prompt = (
        f"You are an expert career advisor with a creative and engaging tone. "
        f"Develop a highly personalized, actionable career plan based on these inputs:\n"
        f"- **Engineering Education**: {education} (leverage this background uniquely)\n"
        f"- **Skills**: {skills} (highlight specific strengths and gaps)\n"
        f"- **Internships/Experience**: {internships} (build on this experience creatively)\n"
        f"- **Interests**: {interests} (tailor the plan to these passions)\n\n"
        f"Structure the plan with these sections:\n"
        f"- **Short-term Steps (1-2 years)**: 3-4 practical steps to kickstart their career.\n"
        f"- **Long-term Vision (3-5 years)**: 3 ambitious steps to advance their path.\n"
        f"- **Target Roles**: 3 specific job titles with a brief description.\n"
        f"- **Skills to Master**: 3-4 skills with why they matter.\n"
        f"- **Top Resources**: 3 specific recommendations (courses, books, tools).\n"
        f"Make the plan concise, vivid, and unique to the inputs—avoid generic advice!"
    )

    try:
        # Initialize the Gemini model
        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(prompt)
        
        if not response.text:
            return "⚠️ **Error**: No response generated. Check API key or model availability."
        
        # Enhance output formatting
        formatted_output = (
            f"## 🚀 Your Tailored Career Blueprint\n\n"
            f"{response.text}\n\n"
            f"---\n"
            f"*Generated by Google Gemini on {os.getenv('CURRENT_DATE', 'March 31, 2025')}*"
        )
        return formatted_output
    except Exception as e:
        return f"⚠️ **Error**: {str(e)}. Check your API key or network connection."

# Custom CSS for styling
custom_css = """
    .gr-button { background-color: #4CAF50; color: white; border-radius: 8px; }
    .gr-textbox { border-radius: 5px; }
    .gr-markdown h2 { color: #2E7D32; }
    .gr-markdown h3 { color: #388E3C; border-bottom: 2px solid #81C784; }
    .gr-markdown { font-family: 'Arial', sans-serif; }
"""

# Gradio interface with enhancements
with gr.Blocks(
    title="Career Guidance Chatbot",
    theme=gr.themes.Soft(primary_hue="green", secondary_hue="blue"),
    css=custom_css
) as demo:
    gr.Markdown(
        """
        # 🌟 Career Guidance Chatbot
        Get a **personalized career plan** tailored to your unique profile, powered by Google Gemini.  
        Fill in the details below and watch your future take shape!
        """
    )
    
    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### 📋 Your Profile")
            education = gr.Textbox(
                label="Engineering Education",
                placeholder="e.g., Computer Science, Mechanical",
                lines=1
            )
            skills = gr.Textbox(
                label="Skills",
                placeholder="e.g., Python, CAD, project management",
                lines=2
            )
            internships = gr.Textbox(
                label="Internships/Experience",
                placeholder="e.g., 3 months at XYZ Corp",
                lines=2
            )
            interests = gr.Textbox(
                label="Interests",
                placeholder="e.g., AI, robotics, sustainable energy",
                lines=2
            )
            submit_btn = gr.Button("Generate My Plan", variant="primary")
        
        with gr.Column(scale=2):
            gr.Markdown("### 📈 Your Career Plan")
            output = gr.Markdown(
                value="Fill out the form and click 'Generate My Plan' to see your customized career roadmap!"
            )
    
    # Add loading state
    submit_btn.click(
        fn=generate_career_plan,
        inputs=[education, skills, internships, interests],
        outputs=output,
        _js="() => { document.body.style.cursor = 'wait'; setTimeout(() => document.body.style.cursor = 'default', 5000); }"
    )

# Launch the app
demo.launch()